#spring:
#  security:
#    user:
#      name: in28minutes
#      password: dummy
spring:
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  #executes data.sql after the database initialization
  jpa:
    defer-datasource-initialization: true