spring:
  jpa:
    defer-datasource-initialization: true
    show-sql: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb

logging:
  level:
    com:
      in28minutes: info